version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@legaltech.ovh"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certificates:/letsencrypt
    networks:
      - legaltech_network
    deploy:
      placement:
        constraints:
          - node.role == manager

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: legaltech
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: legaltech
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/scripts/init-phase1-shared.sh:/docker-entrypoint-initdb.d/init-phase1-shared.sh:ro
      - ./database/scripts/init-phase2-demo.sh:/docker-entrypoint-initdb.d/init-phase2-demo.sh:ro
      # - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      # - ./database/init-shared-schema.sql:/docker-entrypoint-initdb.d/init-shared-schema.sql:ro
      # - ./database/create-tenant-tables.sql:/docker-entrypoint-initdb.d/create-tenant-tables.sql:ro
    networks:
      - legaltech_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Backend for demo tenant
  backend_demo:
    image: legaltech-backend:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "false"
      TENANT_SCHEMA_MAPPING: '{"demo":"tenant_demo","abc":"tenant_abc"}'
      DOCUMENT_STORAGE_PATH: /app/storage
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      SUPER_ADMIN_API_KEY: ${SUPER_ADMIN_API_KEY:-change-me-in-production}
    volumes:
      - document_storage:/app/storage
    networks:
      - legaltech_network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # HTTPS router
        - "traefik.http.routers.backend_demo.rule=Host(`demo.legaltech.ovh`) && PathPrefix(`/api`, `/health`, `/docs`)"
        - "traefik.http.routers.backend_demo.entrypoints=websecure"
        - "traefik.http.routers.backend_demo.tls.certresolver=letsencrypt"
        - "traefik.http.routers.backend_demo.priority=2"
        # HTTP router (redirect to HTTPS)
        - "traefik.http.routers.backend_demo_http.rule=Host(`demo.legaltech.ovh`) && PathPrefix(`/api`, `/health`, `/docs`)"
        - "traefik.http.routers.backend_demo_http.entrypoints=web"
        - "traefik.http.routers.backend_demo_http.middlewares=redirect-to-https"
        - "traefik.http.routers.backend_demo_http.priority=2"
        # Redirect middleware
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
        # Service
        - "traefik.http.services.backend_demo.loadbalancer.server.port=8000"
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  # Frontend for demo tenant
  frontend_demo:
    image: legaltech-frontend:latest
    networks:
      - legaltech_network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # HTTPS router
        - "traefik.http.routers.frontend_demo.rule=Host(`demo.legaltech.ovh`)"
        - "traefik.http.routers.frontend_demo.entrypoints=websecure"
        - "traefik.http.routers.frontend_demo.tls.certresolver=letsencrypt"
        - "traefik.http.routers.frontend_demo.priority=1"
        # HTTP router (redirect to HTTPS)
        - "traefik.http.routers.frontend_demo_http.rule=Host(`demo.legaltech.ovh`)"
        - "traefik.http.routers.frontend_demo_http.entrypoints=web"
        - "traefik.http.routers.frontend_demo_http.middlewares=redirect-to-https"
        - "traefik.http.routers.frontend_demo_http.priority=1"
        # Service
        - "traefik.http.services.frontend_demo.loadbalancer.server.port=80"
      restart_policy:
        condition: on-failure
    depends_on:
      - backend_demo

  # Backend for abc tenant
  backend_abc:
    image: legaltech-backend:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "false"
      TENANT_SCHEMA_MAPPING: '{"demo":"tenant_demo","abc":"tenant_abc"}'
      DOCUMENT_STORAGE_PATH: /app/storage
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      SUPER_ADMIN_API_KEY: ${SUPER_ADMIN_API_KEY:-change-me-in-production}
    volumes:
      - document_storage:/app/storage
    networks:
      - legaltech_network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # HTTPS router
        - "traefik.http.routers.backend_abc.rule=Host(`abc.legaltech.ovh`) && PathPrefix(`/api`, `/health`, `/docs`)"
        - "traefik.http.routers.backend_abc.entrypoints=websecure"
        - "traefik.http.routers.backend_abc.tls.certresolver=letsencrypt"
        - "traefik.http.routers.backend_abc.priority=2"
        # HTTP router (redirect to HTTPS)
        - "traefik.http.routers.backend_abc_http.rule=Host(`abc.legaltech.ovh`) && PathPrefix(`/api`, `/health`, `/docs`)"
        - "traefik.http.routers.backend_abc_http.entrypoints=web"
        - "traefik.http.routers.backend_abc_http.middlewares=redirect-to-https"
        - "traefik.http.routers.backend_abc_http.priority=2"
        # Service
        - "traefik.http.services.backend_abc.loadbalancer.server.port=8000"
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  # Frontend for abc tenant
  frontend_abc:
    image: legaltech-frontend:latest
    networks:
      - legaltech_network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # HTTPS router
        - "traefik.http.routers.frontend_abc.rule=Host(`abc.legaltech.ovh`)"
        - "traefik.http.routers.frontend_abc.entrypoints=websecure"
        - "traefik.http.routers.frontend_abc.tls.certresolver=letsencrypt"
        - "traefik.http.routers.frontend_abc.priority=1"
        # HTTP router (redirect to HTTPS)
        - "traefik.http.routers.frontend_abc_http.rule=Host(`abc.legaltech.ovh`)"
        - "traefik.http.routers.frontend_abc_http.entrypoints=web"
        - "traefik.http.routers.frontend_abc_http.middlewares=redirect-to-https"
        - "traefik.http.routers.frontend_abc_http.priority=1"
        # Service
        - "traefik.http.services.frontend_abc.loadbalancer.server.port=80"
      restart_policy:
        condition: on-failure
    depends_on:
      - backend_abc

networks:
  legaltech_network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
  traefik_certificates:
  document_storage:
