version: '3.8'

# =============================================================================
# Portainer - Docker Swarm Management UI
# =============================================================================
#
# Deploy: docker stack deploy -c docker-stack.portainer.yml portainer
#
# SECURITY: localhost-only access enforced via iptables DOCKER-USER chain
#
# After deploying, run these commands to restrict access to localhost only:
#
#   # Allow localhost access to Portainer
#   sudo iptables -I DOCKER-USER -i lo -p tcp --dport 9443 -j ACCEPT
#
#   # Drop all other access to Portainer
#   sudo iptables -I DOCKER-USER -p tcp --dport 9443 -j DROP
#
# To persist across reboots:
#
#   sudo apt install iptables-persistent
#   sudo netfilter-persistent save
#
# To access via SSH tunnel from your laptop:
#
#   ssh -L 9443:127.0.0.1:9443 user@vps-ip
#   # Then open https://localhost:9443 in browser
#
# =============================================================================

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - portainer_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure

networks:
  portainer_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/data/portainer
