version: '3.8'

# =============================================================================
# Portainer - Docker Swarm Management UI
# =============================================================================
#
# Deploy: docker stack deploy -c docker-stack.portainer.yml portainer
#
# SECURITY: localhost-only access enforced via iptables DOCKER-USER chain
#
# After deploying, run these commands to restrict access to localhost only:
#
#   # Allow localhost access to Portainer
#   sudo iptables -I DOCKER-USER -i lo -p tcp --dport 9000 -j ACCEPT
#
#   # Drop all other access to Portainer
#   sudo iptables -I DOCKER-USER -p tcp --dport 9000 -j DROP
#
# To persist across reboots:
#
#   sudo apt install iptables-persistent
#   sudo netfilter-persistent save
#
# To access via SSH tunnel from your laptop:
#
#   ssh -L 9000:127.0.0.1:9000 user@vps-ip
#   # Then open http://localhost:9000 in browser
#
# =============================================================================

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - portainer_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
  # Log monitoring with Dozzle
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "127.0.0.1:8888:8080"  # Only localhost access (for SSH tunnel)
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "name=legaltech_"
      DOZZLE_NO_ANALYTICS: "true"
    networks:
      - legaltech_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      restart_policy:
        condition: on-failure 
networks:
  portainer_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/data/portainer
